Ahora que estamos en Navidades y se acercan los reyes seguro que a más de uno le van a llover unos gatos nuevos. Os damos unas impresiones (ojo son opiniones y para gustos están los colores) de los gatos que hemos probado en las últimas fechas. Repito que son nuestras valoraciones y lo que a uno le puede parecer increíble a otros les puede parecer simplemente mediocre. Vamos a ello!<br />
Comenzamos con el Tenaya Inti, un gato que muchos esperabamos como una mejora de los Ra, o al menos así lo venden. El Ra es un gato muy polivalente que ha dado un resultado más que bueno comparando su precio con otros del mercado y prueba de ello es la cantidad de ellos que se ven por las diferentes escuelas de nuestra geografía.<br />
<?php photo::print_photo_blog(450); ?>
Aparentemente son iguales, salvando la estética que normalmente nos suele dar igual pero hay una gran diferencia que hace que a nosotros el Inti nos parezca simplemente mediocre...Y es su rigidez a torsión, si, esa tan necesaria para apoyarnos en ínfimas regletas y cantear de manera segura sin que se te pire el pie. El Ra si que posee esa rigidez y lo digo porque calzo unos (sin ser comparable a la de unos Miura es más que aceptable) pero cuando te metes en los Inti es como si le hubieran quitado la suela y la horma fuera mucho más blanda. Cagadón, si lo que quieres es regletear estos no son los gatos. El modelo Ra, es un gato que sin ser el mejor destaca por su polivalencia y por un detalle que personalmente me gusta mucho: su facilidad para ser calzado ya que se abre completamente y hablo comparándolo con unos Miura que al ser mucha más rígida la horma no permite calzartelos tan fácilmente. Por supuesto que los Miura son mucho más punteros y técnicos pero por 80 € de los Ra (60 € en Barrabés antes del verano...) es un gato que creo que al público general le gusta bastante.<br />
<?php photo::print_photo_blog(451); ?>
El Inti como digo, hereda la mayoría de los rasgos del Ra, con una horma ligeramente más estrecha pero la misma goma Vibran XS Grip de 4mm. Todo similar salvo la rigidez necesaria para cantear. Cada uno que juzgue pero yo no me los compraría.<br />
Pasamos ahora a ver los Evolv Bandit, que actualmente rondan los 90 € y no se ven demasiados por nuestras tierras. Un hecho que llama la atención, al menos parece una estragia comercial es que al menos el 30 % de su goma proviene de material reciclado, es la goma EcoTrax. El Bandit, en nuestros pies nos pareció un gato todoterreno bastante cómodo. El cierre es de cordones cosa que personalmente no me gusta excesivamente pero si quieres el mejor ajuste, ésta es la forma. El talón ajusta bastante bien, a diferencia de otros gatos ya consagrados como los Anasazi de 5.10 (nunca he entendido el motivo de este talón tan raro...)<br />
<?php photo::print_photo_blog(452); ?>
La goma que a priori es una gran desconocida para nosotros ha funcionado perfectamente y despejó todas las dudas que podíamos tener inicialmente. Se trata de un gato medianamente rígido pero a pesar de ello, lo puedes llevar durante horas que tu pie a penas sufrirá. Quizás sea este una buena alternativa para aquellos que sufren de los pies y no quieren algo excesivamente técnico.<br />
<?php photo::print_photo_blog(453); ?>
Nuestro último gato es uno muy económico, de lo que ya no te encuentras en el mercado. Se trata de los Garra Caribe. Es un gato bastante rígido con goma Vibram pero la chunga, realmente una goma muy muy dura quizás con calor se le saque más partido. De corte técnico con velcros es una opción económica para entrenar en roco o para aquellas vías en que no quieres destrozar tus gatos buenos. Parecen una buena compra por un precio muy asequible.<br />
<?php photo::print_photo_blog(454); ?>
<?php photo::print_photo_blog(455); ?>
Más info en <a href="http://www.garra.info/">http://www.garra.info/</a><br />
Al final con tantos pies de gato siempre tienes que ir cargando con dos pares para elegir los más adecuados. Está claro que "los buenos" no necesitan del mejor pie de gato pero el resto de los mortales necesitamos atinar con el gato perfecto. El mercado es muy amplio y hay gran variedad. La mejor forma es irse a la tienda y probar los que mejor te queden, tocarlos, torsionarlos, flexionarlos y pillarte el que mejor se adapte a tus necesidades. Quizás estas opiniones os puedan orientar en vuestra decisión. Suerte!<br />

