El mercado de los friends para escalada actualmente es muy amplio y variado, tanto que a veces nos cuesta decidirnos por qué modelo escoger para nuestras rutas, y es que después de mucho leer, buscar y probar, la conclusión es clara: No existe el friend perfecto.<br />
En cualquier caso, vamos a tratar de despejar ulgunas dudas sobre uno de los principales competidores de los Alien, el bestseller del mercado de los microfriends. Se trata de los Black Diamond Camalot C3. <br />
Por todos son conocidos los Camalot C4 de 4 levas por ser uno de los "más usados" en nuestras escaladas y es que la fiabilidad, el tacto y especialmente el rango de apertura lo han consolidado a lo largo de los años como uno de los mejores cams para clásica. En cuanto a su hermano pequeño, el C3, un friend de 3 levas, si bien se ven bastante, sin duda el más usado hasta la fecha ha sido el Alien. Por su puesto que habrá gente que ni quiera oir hablar del término microfriends, "Antaño subíamos con tacos de madera y martillo", para ellos están los empotradores, muy útiles, pero totalmente inservibles en ciertos tipos de roca y fisuras, y como la tecnología evoluciona, qué mejor que hacerse con un par de microfriends que nos van a salvar de más de una situación complicada.<br />
Comenzamos..<br />
<?php photo::print_photo_blog(499); ?>
El gran rival del C3 es sin duda el Alien, durante unos añitos la mítica marca americana CCH desapareció y era complicado encontrar estas piezas en el mercado pero recientemente Fixe se hizo con la patente y comenzó la producción del clásico Alien. Actualmente se venden por un precio de 68 leuros. Puesto que la patente ya había caducado han aparecido otras versiones, prácticamente calcadas, del original Alien, la marca Totem TM comercializa su Basic Cam por un precio de 60 euros.
Si analizamos el C3 podemos encontrar a simple vista con un diseño bastante robusto y muy buenos acabados, como no podía ser de otra manera para la marca americana. Una gran empresa como Black Diamond inspira confianza, aunque ya hemos visto como grandes empresas en este mundo la han cagado con ciertos productos y como por ejemplo Petzl, si bien el potencial de una gran empresa para corregir esos errores es grande, y al menos a mi me tranquiliza pensar que en un sitio como este se hacen rigurosos controles de calidad y si hay un gazapo como ha ocurrido antes, tenemos garantizado que nuestra pieza será corregida de inmediato. Por todos es sabido también los problemas que han tenido los Aliens en el pasado si bien su uso más que generalizado es uno de los puntos fuertes que a mi me tranquiliza, aunque la duda que me surge es si las empresas que actualmente lo fabrican tienen los medios de control que el gigante americano.<br />
<?php photo::print_photo_blog(489); ?>
Dicen las malas lenguas, que el C3 obtiene su diseño, como resultado de esquivar la patente del vástago flexible de los Aliens, y esto tiene cierta lógica... Sin embargo, el sistema de BD (Black Diamond a partir de ahora) tiene importantes mejoras frente al Alien y por supuesto algunos grandes defectos que vamos a comentar a continuación.<br />
<?php photo::print_photo_blog(490); ?>
Por lo pronto, en cuanto a los materiales empleados no se especifica en ningún lado. Es un misterio supongo que por intereses comerciales, aunque a muchos de nosotros nos interesa saber un poco más de esos pequeños cacharros. Me puse en contacto con Black Diamond en referencia a este tema, pero la respuesta fue negativa, dicen no poder desvelar de momento que tipo de aluminio utilizan en sus friends salvo que hay tres tipos de aluminio dependiendo del cam y la localización (palabras textuales...). Entiendo que en los más pequeños habrán utilizado aluminio más blando para mejorar la adherencia a costa de la resistencia aunque esto son elucubraciones.<br />
<?php photo::print_photo_blog(497); ?>
Rebuscando en la red, he encontrado una web que dice que probablemente han empleado una aleación 6061 para los más canis y 7075 para los dos más grandes. Por si alguien no lo sabe, ambos son aleaciones de aluminio empleadas comunmente en las bicicletas de montaña. El primero se utiliza cuando se requiere soldadura o un fácil mecanicado debido a su relativa buena trabajabilidad. Así mismo este aluminio, sería el encargado de dar un extra al "grip" o adherencia del metal contra la roca dado su relativa facilidad de deformación. Esto podemos comprobarlo en los Aliens que utilizan esta aleación en sus levas y con un uso prolongado, las muescas en las mismas van redondeandose e incluso desapareciendo. Por otro lado el 7075 es bastante más duro y también es de uso común en la aviación y podría ser el elegido para los dos números más grandes (aparecen las muescas y aumenta notablemente la resistencia lo que nos incita a pensar que vamos por el buen camino).Esto son suposiciones y hay que tomarlas como tal pero es probable que algunos de los 3 aluminios empleados sean estos que comentamos por su uso común en material de este tipo.<br />
<?php photo::print_photo_blog(492); ?>
Como hemos comentado, los tres números más pequeños, el triple cero, doble cero y cero, no tienen serrajes en sus levas tema que entiendo será para aumentar la superficie de rozamiento con la roca que dado el pequeño tamaño de los artilugios es excaso. Esto es un tema importante, y a priori, las tres levas que utilizan estos friends nos incita a pensar que logicamente darán menos superficie de contacto que un friend de 4 levas. No ocurre así dado el diseño del sistema ya que las levas son más anchas que las utilizadas en un friend de 4 como puede ser el Alien. Otros sistemas de tres levas como el Ultralight TCU de Metolius comparten estas cualidades y su fiabilidad está más que contrastada. Sin embargo, esta afirmación no es del todo cierta ya que si el friend está bastante abierto la sección de las levas en contacto con la roca es menor y efectivamente en este caso dan menos superficie. En cualquier caso, tras probarlo en diferentes emplazamientos, la sección crítica la da el friend con las levas más cerradas y aquí efectivamente el aumento de superficie es considerable, punto importante a tener en cuenta.<br />
<?php photo::print_photo_blog(491); ?>
Otro detalle en cuanto a las levas es que extendidas se bloquean unas con otras. Esto a priori nos hace pensar que se podría utilizar en modo pasivo abierto como un stopper pero leyendo las instrucciones deja claro que no es un uso que pueda darse.<br />
Uno de los puntos fuertes del Camalot C3 es el ancho de la cabeza, realmente compacto debido a la superposición de las 3 levas, esto nos va a permitir colocarlo en pequeños agujeros que con otro microfriend de 4 levas sería imposible.<br />
En cuanto a la resistencia y el peso, los números son mejores que otros microfriends, comparando el BD C3 #2 (Black Diamond C3 número 2) con el Alien Verde 1/2 observamos que no sólo pesan menos sino que dan más resistencia. Incluso el siguiente número del Alien Amarillo 3/4 da 900 kg frente a las 1000 del numero 2 de Camalot. Os pongo un comparativo donde podéis ver los rangos de apertura, resistencia y peso de diferentes marcas. Sin tener en cuenta otros datos como precio, flexibilidad y durabilidad los C3s están por encima del resto de los microfriends salvo al Alien Gris. Sin embargo en los números más pequeños, los Zero de WC resultan superiores si bien estos números sólo deben utilizarse para progresión.<br />
<?php photo::print_photo_blog(493); ?>
Comentar un detalle que se especifica en las instrucciones a cerca del clipado del mosquetón. Si utilizas la cinta no tienes problemas pero si chapas directamente a la oreja estás reduciendo la resistencia en 200 kilos nada más y nada menos. No se si esto ocurrirá en otros friends pero no recuerdo ver nada especificado en otras marcas y sin embargo esta zona suele ser muy similar en todos...hay que tener esto en cuenta. Ojo también si unimos la cinta existe a otra puesto que estaremos reduciendo la resistencia del sistema enormemente. En diversos ensayos se han llegado a reducciones de hasta el 50 % de la resistencia inicial. <a href="http://www.blackdiamondequipment.com/en-us/journal/climb/all/qc-lab-connecting-two-slings-together">Aquí</a> podéis encontrar más info.<br />  
<?php photo::print_photo_blog(494); ?>
Como puntos negativos de este aparato tenemos la flexibilidad que es lo que hace que los Alien y sistemas similares de vástago flexible se lleven la palma frente a estos. Los C3 doblan bien en sentido horizontal pero bastante mal en el vertical. Realmente en el sentido perpendicar no flexan por lo que el friend se retuerce sobre si mismo para poder soportar las fuerzas que se le imponen. Esto está pensado así y a priori podría parecer que el friend no lo va a soportar pero realmente aguanta. Hay una posición claramente desaconsejada en las instrucciones que es una fisura vertical en la que sólo podemos colocar el friend en horizontal. Sería como la hendidura de un viejo clavo que aprovechamos para meter el friend. Como ocurre con sus hermanos mayores, hay que saber emplazar estos aparatos, antaño los vástagos rígidos nos obligaban a pensar y rebuscar hasta encontrar el sitio idóneo con la orientación adecuada ante una eventual caída. Con la introducción de los vástagos flexibles nos hemos ido acomodando y ya casi ni pensamos. Cierto es que en el mundo de las microfisuras la flexibilidad es casi una exigencia y en ocasiones no queda otra que colocar el aparato como se pueda pero sabiendo lo que se puede y no se puede hacer puede resultar un mal menor debido a esa capacidad antes comentada. Un Camalot ante una fuerza como la anteriormente comentada hará que se retuerza sobre su eje provando una torsión añadida a la fuerza del impacto de la caída. Las cabeza experimentará un movimiento haciendo que las levas superiores intenten salir hacia fuera y las inferiores meterse dentro. Este cabeceo sin embargo también lo experimentará un Alien ante la misma caída pero no el momento (fuerza por distancia) generado por la palanca que sí hace el Camalot. Punto negativo para los C3. A parte de los Alien, tenemos los Zero de Wild Country, microfriends incluso más flexibles que los propios Alien si este es el punto que más nos interesa.<br />
<?php photo::print_photo_blog(496); ?>
En cuanto al tacto de los C3 es muy bueno, y cómodo de tirar del gatillo. Sin embargo, puede resultar algo duro en los números grandes y consecuentemente difícil de sacarlo de la fisura. En los Alien el tacto no es malo tampoco pero si algo más incómodo debido a la forma del tirador. Los Ultralight TCU tienen algo que en mi opinión es una gran defecto y no entiendo como no han cambiado el sistema. Más de una vez lo hemos comentado que al emplazar los un friend de este tipo, rollo los Camalot antiguos, o los DMM antiguos o estos de los que os hablo, cuando introduces el aparato en una fisura que se va estrechando en la que tienes que meter la mano hasta el fondo para amarrar el friend en ciertas ocasiones se te queda enganchado el dedo gordo por la posición de la mano. A varios de nosotros nos ha ocurrido varias veces y en un paso comprometido lo que menos quieres es pelearte para sacar la mano te una situación tan ridícula como esta.<br />
<?php photo::print_photo_blog(498); ?>
La cinta empleada posee un reenvío que cuando menos parece curioso, pero tiene un motivo bien justificado. <a href="http://www.blackdiamondequipment.com/en-us/journal/climb/knowledge/qc-labreslinging-camalots-and-c3s">Aquí</a> podéis encontrar el por qué pero básicamente se trata de evitar la deformación del cable de la oreja. En ese documento encontraréis fotos bastante llamativas por ejemplo cuando utilizamos una cinta doble extensible muy habitual en clásica en donde el friend falla a cargas muy inferiores a las esperadas.<br />
<?php photo::print_photo_blog(495); ?>
En cuanto a la durabilidad, de eso no os puedo hablar porque la adquisición es bastante reciente pero a priori parecen bastante sólidos. Sólo me cabe la duda del mantenimiento a la hora de cambiar los tiradores ya que van protegidos con el plástico ese y no se yo que clase de operación de cirugía habrá que hacer para biseccionarlos.<br />
Otro gran punto negativo es el precio de estos aparatos. Rondando los 72 euros aquí en España muchos usuarios se van a tirar por el archiconocido Alien.<br />
Para concluir podemos resumir a modo de ventajas una mayor resistencia y menor peso para el mismo rango de apertura, un menor tamaño de cabeza lo que amplía los sitios de colocación, una superficie de contacto en principio mayor que uno de 4 levas, así como la existencia de números pequeños aunque sólo para progresión. Como desventajas su flexión en una sóla dirección y su precio superior.<br />
Nosotros adquirimos el C3 0, el C3 2 y el C4 0.4 para completar nuestro juego de friends en USA y nos salieron por 42 € cada uno, un precio muy inferior a los 75 € de España. Si tuviera que comprarmelos aquí en España dudaría dado el precio y las características antes comentadas.<br />
Ahora cada uno que elija lo que mejor se adapta a sus necesidades y, buenas escaladas! 


