<table width="80%" border="0" cellpadding="4" cellspacing="4" align="center">
  <tr>
    <td><div class="standard_container default_text"> <span class="standard_cont_title">CONDICIONES GENERALES DE USO DEL SITIO WEB www.rocaya.com</span><br />
      <div class="default_text indented">Rocaya.com ofrece información sobre el mundo de la escalada, croquis de vías totalmente realizados por nosotros, fotografías, estadísticas, comentarios, reportajes y un foro en el que los usuarios pueden verter sus opiniones.<br>
        Las presentes condiciones generales rigen única y exclusivamente el uso de la web propiedad de rocaya por parte de los USUARIOS que accedan a la misma y estas condiciones son presentadas al USUARIO a través de este sitio web debiendo este leerlas y aceptarlas.<br>
        <br>
        El acceso al sitio web de www.rocaya.com implica sin reservas la aceptación de las presentes condiciones generales de uso y el USUARIO manifiesta haber leído y comprendido las mismas y se compromete no a utilizar la página y las informaciones contenidas en la misma para la realización de actividades contrarias a la ley y a respetar las presentes condiciones generales.<br>
        <br>
        PRIMERA.- El sitio web de rocaya ha sido realizado para ofrecer información sobre escalada y otros deportes de aventura y fomentar la participación de los usuarios así como crear una comunidad interesada en los temas comunes y más concretamente en el deporte de la escalada. La escalada es un deporte de riesgo y como tal, sus practicantes deben conocer el equipo, las técnicas y los riesgos completamente antes iniciar la actividad. Así pues, los contenidos de esta web son meramente informativos por lo que será el USUARIO quien los interprete y haga mejor uso de ellos, declinando toda responsabilidad <a href="http://rocaya.com/">rocaya.com</a> de posibles accidentes por un mal uso de la información que aquí se expone.<br>
        <br />
        SEGUNDA.- CONDICIONES DE ACCESO Y USO: Las condiciones de acceso y uso de la presente web se rigen estrictamente por la legalidad vigente y por el principio de buena fe comprometiéndose el USUARIO a realizar un buen uso del sitio web. Quedan por tanto prohibidos todos los actos que vulneren la legalidad, derechos o intereses de terceros: derecho a la intimidad, protección de datos, propiedad intelectual etc. Expresamente Rocaya.com prohíbe los siguientes:<br>
        • realizar sin la debida autorización cualquier tipo de publicidad o información comercial directamente o de forma encubierta, el envío de correos masivos ("spamming") o envío de grandes mensajes con el fin de bloquear servidores de la red ("mail bombing")<br>
        • realizar acciones que puedan producir en la web o a través de la misma por cualquier medio cualquier tipo de daño a Rocaya.com o a terceros<br>
        Rocaya.com podrá interrumpir en cualquier momento el acceso a su sitio web si detecta un uso contrario a la legalidad, la buena fe o a las presentes condiciones generales- ver cláusula sexta.<br>
        <br />
        TERCERA.- CONTENIDOS: Los contenidos, tanto gráficos como escritos incorporados en este sitio web han sido elaborados e incluidos por:<br>
        • Rocaya.com utilizando fuentes internas y externas de tal modo que el propietario del sitio web www.rocaya.com únicamente se hace responsable por los contenidos elaborados de forma interna por él mismo. En todo caso, los croquis realizados deben entenderse como una aproximación a la ruta real, y por tanto puede contener errores tanto en el trazado como en el nombre de la vía, su graduación y equipamiento. Por tanto, son los USUARIOS quienes deben interpretar esta información y no tomarla como estricta.<br>
        • Los USUARIOS, a través de colaboraciones o introducción voluntaria de contenidos, tanto gráficos como escritos, siendo éstos los únicos responsables de los mismos y quedando expresamente exenta rocaya.com de toda responsabilidad. EL USUARIO que introduzca cualquier contenido en el sitio web de rocaya.com manifiesta la absoluta legalidad y autoría de los mismos y expresamente asume todo tipo de responsabilidad que se pueda derivar de estos contenidos. El USUARIO introduce estos contenidos a través del foro, y en las secciones de fotografías, croquis y reportajes, introduciendo datos básicos una vez se lean las presentes condiciones. Rocaya.com no será responsable en ningún caso de las opiniones vertidas en los referidos foros y podrá retirar o impedir el acceso a los USUARIOS que vulneren la legalidad vigente así como poner en conocimiento de Juzgados y Tribunales los hechos que sean constitutivos de algún tipo de ilícito penal o civil. Los USUARIOS serán los únicos poseedoros de los derechos de las fotografías subidas asi bien rocaya.com podrá reproducir, copiar o utilizar las fotografías para su propio interés. <br>
        • personas físicas y jurídicas ajenas a Rocaya.com, bien a través de colaboraciones que se insertan directamente en la presente web, bien a través de enlaces o links, siendo éstas las únicas responsables de los contenidos así introducidos y quedando expresamente exento Rocaya.com de toda responsabilidad.<br>
        Rocaya.com se reserva la facultad de efectuar, en cualquier momento y sin previo aviso, modificaciones y supresiones de la información contenida en su sitio web. Las modificaciones tan sólo las realizará sobre sus contenidos propios pero se reserva la facultad de efectuar supresiones de participaciones de USUARIOS con el fin de actualizar el sitio web.<br>
        Rocaya.com no garantiza que los enlaces o links creados en el sitio web del que es propietario sean exactos en el momento de acceso de un USUARIO así como la exactitud en la información sobre vías de escalada.<br>
        <br />
        CUARTA.- REGISTRO Y PARTICIPACIÓN EN EL ENVÍO DE CONTENIDOS: La utilización de la web de Rocaya.com no conlleva la obligatoriedad de registro del USUARIO; sin embargo el USUARIO que desee introducir contenidos a través del foro y participar en el mismo, además de poder registrar sus ascensiones en las diferentes vías deberá cubrir a través del sitio web un formulario introduciendo una serie de datos básicos para poder efectuar esta participación. <br>
        <br />
        QUINTA.- PROTECCIÓN DE DATOS: En relación con los datos de carácter personal facilitados por el USUARIO en el formulario de registro (Nombre y correo), estos son almacenados en la base de datos de Rocaya.com y en ningún caso serán facilitados a terceros.<br>
        Los datos sobre ascensiones son utilizados por el propio usuario para sus estadísticas personales.<br>
        El USUARIO tendrá pleno derecho a ejercitar sus derechos de acceso, rectificación, cancelación y oposición en cualquier momento solicitándolo. En todo caso, Rocaya.com se compromete a cancelar los datos personales recabados cuando hayan dejado de ser necesarios o pertinentes para la finalidad para la cual fueron recogidos.<br>
        Seguridad.- Rocaya.com asegura la absoluta confidencialidad y privacidad de los datos personales recogidos y por ello se han adoptado medidas básicas de seguridad para evitar la alteración, pérdida, tratamiento o acceso no autorizado y garantizar así su integridad y seguridad. Sin embargo, Rocaya.com no puede garantizar plenamente la invulnerabilidad absoluta de sus sistemas de seguridad puesto que ninguna medida de seguridad que se instale puede ser en la actualidad inquebrantable, por tanto Rocaya.com no será responsable en ningún caso de las incidencias que puedan surgir en torno a los datos personales cuando se deriven bien de un ataque o acceso no autorizado a nuestros sistemas de tal forma que sea imposible detectarlo por nuestros sistemas de seguridad. Concretamente Rocaya.com no garantiza que terceros no autorizados que realicen cualquier tipo de ataque al sistema puedan tener conocimiento de las características del uso que los USUARIOS hacen del sitio web. <br>
        Las contraseñas de los usuarios se almacenan encriptadas en la base de datos de forma que Rocaya.com nunca conocerá el valor original de las mismas.<br>
        Spamming.- Rocaya.com es contrario al spamming y nunca lo realizará tampoco permitirá su uso por los usuarios del sitio web. +info: http://spam.abuse.net<br>
        El usuario es responsable de la veracidad de sus datos, comprometiéndose a no introducir datos falsos y a proceder a la modificación de los mismos si fuera necesario.<br>
        <br />
        SEXTA.- Rocaya.com además de las exenciones de responsabilidad que constan en las distintas cláusulas de las presentes condiciones, en ningún caso será responsable:<br>
        • de la producción de cualquier tipo de daño que los USUARIOS o terceros pudiesen ocasionar en el sitio web, reservándose Rocaya.com el derecho a suspender el acceso sin previo aviso de forma discrecional y con carácter definitivo o temporal hasta el aseguramiento de la efectiva responsabilidad de esos daños. Asimismo, Rocaya.com colaborará y notificará a la autoridad competente estas incidencias en el momento en que tenga conocimiento fehaciente de que los daños ocasionados constituyan cualquier tipo de actividad ilícita.<br>
        • de la fiabilidad y veracidad de las informaciones introducidas por terceros en el sitio web, bien directamente, bien a través de enlaces o links ni de las posibles incidencias que el USUARIO pueda tener al ponerse en contacto o utilizar los servicios de estos terceros. Rocaya.com, tan sólo ofrece contenidos informativos y de contacto de estos servicios sin responsabilizarse en ningún caso de los mismos. Asimismo, Rocaya.com colaborará y notificará a la autoridad competente estas incidencias en el momento en que tenga conocimiento fehaciente de que los daños ocasionados constituyan cualquier tipo de actividad ilícita.<br>
        <br />
        SÉPTIMA.- DERECHOS DE AUTOR.- El sitio web de Rocaya.com, los contenidos propios tanto gráficos como escritos, la programación y el diseño, se encuentra plenamente protegido por los derechos de autor siendo él mismo quien lo edita, maqueta, reproduce y divulga bajo su nombre constituyendo así una creación original. Los contenidos propios del sitio web podrán utilizarse, reproducirse y comunicarse por cualquier medio, todo o parte del sitio web de manera libre y gratuita, siempre que se cite expresamente la procedencia. +info: http://www.gnu.org/copyleft/copyleft.es.html<br>
        <br />
        OCTAVA.- JURISDICCIÓN Y LEY APLICABLE.- Las presentes condiciones generales se rigen por la legislación española. Toda controversia o conflicto que se derive de las presentes condiciones generales se resolverá definitivamente, mediante arbitraje de uno o más árbitros en el marco de la Corte Española de Arbitraje, de conformidad con su reglamento y Estatuto, a la que se encomienda la administración del arbitraje y la designación del árbitro o del tribunal arbitral. Las partes hacen constar su compromiso de cumplir el laudo arbitral que se dicte. Subsidiariamente para el caso de que esta vía no llegue a solucionar definitivamente el conflicto serán competentes para su resolución los Juzgados y Tribunales de Madrid renunciando expresamente el USUARIO a cualquier otro fuero que pudiera corresponderle.<br>
        <br />
        NOVENA.- En caso de que cualquier cláusula del presente documento sea declarada nula, las demás cláusulas seguirán vigentes y se interpretarán teniendo en cuanta las voluntad de las partes y la finalidad misma de las presentes condiciones. Estas condiciones se ponen permanentemente en el sitio web a disposición del USUARIO y se establecen única y exclusivamente en lengua castellana.<br>
        Rocaya.com podrá no ejercitar alguno de los derechos y facultades conferidos en este documento lo que no implicará en ningún caso la renuncia a los mismos salvo reconocimiento expreso por parte de Rocaya.com</div></div></td>
  </tr>
</table>
